name: Lint

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Set up uv
        uses: astral-sh/setup-uv@v10.2.0
      - name: Run ruff
        run: uvx ruff check --output-format=github junifer_data/
